project_id = "ahsadpsvknpsdwgrdecu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.zapier-provision-user]
    verify_jwt = false
  [functions.check-user-eligible]
    verify_jwt = false
  [functions.admin-user-logins]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.send-verification-code]
    verify_jwt = false
  [functions.verify-code-set-password]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
