project_id = "ahsadpsvknpsdwgrdecu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.zapier-provision-user]
    verify_jwt = false
  [functions.check-user-eligible]
    verify_jwt = false
